import { ExperimentTemplate } from "./types";

export const catalog: ExperimentTemplate[] = [
  {
    slug: "no-phone-before-bed",
    title: "Sin móvil después de las 23:00",
    emoji: "🌙",
    category: "Sueño",
    description: "Deja el móvil fuera durante la última parte del día y mide cómo te levantas.",
    durationDays: 14,
    hypothesis: "Dormiré mejor si dejo de mirar el móvil antes de acostarme.",
    metricLabel: "Calidad del sueño",
    metricMin: 1,
    metricMax: 10,
    metricUnit: "/10",
    baseline: 6,
  },
  {
    slug: "no-tiktok-week",
    title: "7 días sin TikTok",
    emoji: "📵",
    category: "Vida digital",
    description: "Quita TikTok durante una semana y observa si cambia tu concentración.",
    durationDays: 7,
    hypothesis: "Tendré más capacidad de concentración sin TikTok.",
    metricLabel: "Concentración",
    metricMin: 1,
    metricMax: 10,
    metricUnit: "/10",
    baseline: 6,
  },
  {
    slug: "deep-work-50-10",
    title: "Deep Work 50/10",
    emoji: "🧠",
    category: "Productividad",
    description: "Trabaja en bloques de 50 minutos con 10 de descanso, sin multitarea.",
    durationDays: 10,
    hypothesis: "Terminaré el día con mayor sensación de productividad.",
    metricLabel: "Productividad",
    metricMin: 1,
    metricMax: 10,
    metricUnit: "/10",
    baseline: 6,
  },
  {
    slug: "morning-workout",
    title: "Entrenar antes de trabajar",
    emoji: "🏋️",
    category: "Energía",
    description: "Mueve tu entrenamiento a primera hora y mide tu energía durante el día.",
    durationDays: 14,
    hypothesis: "Tendré más energía durante el día si entreno por la mañana.",
    metricLabel: "Energía",
    metricMin: 1,
    metricMax: 10,
    metricUnit: "/10",
    baseline: 6,
  },
  {
    slug: "no-spend-week",
    title: "Semana sin compras impulsivas",
    emoji: "💸",
    category: "Dinero",
    description: "Durante siete días compra solo lo planificado y mide tu control del gasto.",
    durationDays: 7,
    hypothesis: "Sentiré mayor control sobre mis gastos si elimino las compras impulsivas.",
    metricLabel: "Control del gasto",
    metricMin: 1,
    metricMax: 10,
    metricUnit: "/10",
    baseline: 5,
  },
  {
    slug: "music-vs-silence",
    title: "Trabajar sin música",
    emoji: "🎧",
    category: "Productividad",
    description: "Trabaja una semana en silencio y compara tu concentración habitual.",
    durationDays: 7,
    hypothesis: "Me concentraré mejor trabajando sin música.",
    metricLabel: "Concentración",
    metricMin: 1,
    metricMax: 10,
    metricUnit: "/10",
    baseline: 6,
  },
];
